sum = 5+2
print("sum =",sum) #addition
diff = 5-2
print("difference =",diff) #subtraction
prod = 5*2
print("product =",prod)  #multiplication
div = 5/2   
print("division =",div) #division
floor_div = 5//2  
print("floor division =",floor_div) #floor division
mod = 5%2  
print("modulus =",mod)  #modulus
exp = 5**2   
print("exponent =",exp) #exponent